-- Furnace reservation schema alignment
-- Run this in Supabase SQL Editor, then reload the project if PostgREST schema cache has not refreshed yet.

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  furnace text not null,
  user_name text,
  start_time timestamp without time zone not null,
  end_time timestamp without time zone not null,
  memo text,
  created_at timestamp with time zone not null default now()
);

alter table public.reservations
  add column if not exists user_names text[] not null default '{}',
  add column if not exists sample_slots jsonb not null default '[]'::jsonb,
  add column if not exists oxygen_pressure numeric,
  add column if not exists firing_temperature integer,
  add column if not exists firing_time_value numeric,
  add column if not exists firing_time_unit text,
  add column if not exists anneal_mode text,
  add column if not exists anneal_start_temp integer,
  add column if not exists anneal_end_temp integer,
  add column if not exists anneal_keep_temp integer,
  add column if not exists anneal_hours integer,
  add column if not exists calcine_slot text;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.samples (
  id bigint generated by default as identity primary key,
  name text not null,
  user_name text,
  created_at timestamp with time zone not null default now()
);

alter table public.samples
  add column if not exists user_name text;

create index if not exists reservations_furnace_start_time_idx
  on public.reservations (furnace, start_time);

create index if not exists reservations_start_time_idx
  on public.reservations (start_time);

create index if not exists users_name_idx
  on public.users (name);

create index if not exists samples_name_idx
  on public.samples (name);

create index if not exists samples_user_name_idx
  on public.samples (user_name);

alter table public.samples
  drop constraint if exists samples_name_key;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'samples_user_name_name_key'
      and conrelid = 'public.samples'::regclass
  ) then
    alter table public.samples
      add constraint samples_user_name_name_key unique (user_name, name);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'reservations_time_order'
      and conrelid = 'public.reservations'::regclass
  ) then
    alter table public.reservations
      add constraint reservations_time_order
      check (end_time > start_time) not valid;
  end if;
end $$;

alter table public.reservations validate constraint reservations_time_order;
